# Generated by Django 4.0.4 on 2022-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0002_remove_artifacts_type_character_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Character_img', verbose_name='Character Image'),
        ),
    ]
