# Generated by Django 4.0.4 on 2022-06-05 20:54

from django.db import migrations, models
import genshin.models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0003_alter_character_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=genshin.models.poster_path, verbose_name='Character Image'),
        ),
    ]
