# Generated by Django 4.0.4 on 2022-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0004_alter_character_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, default='description', help_text="Enter Character's Description: ", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(help_text="Enter Character's Name: ", max_length=50, unique=True, verbose_name='Character Name'),
        ),
    ]
