# Generated by Django 4.0.4 on 2022-06-08 19:22

from django.db import migrations, models
import genshin.models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0005_character_description_alter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=genshin.models.poster_path, verbose_name='Character Image'),
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, default='description', help_text="Enter Region's Description: ", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='region',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=genshin.models.poster_path, verbose_name='Character Image'),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='name',
            field=models.CharField(help_text='Enter Artifact Name: ', max_length=50, unique=True, verbose_name='Artifacts'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Enter Region Name: ', max_length=50, unique=True, verbose_name='Region'),
        ),
    ]
